import test from 'node:test';
import assert from 'node:assert/strict';
import {Worker} from 'node:worker_threads';
import {unzipSync,zipSync,strToU8,strFromU8} from 'fflate';
import {writeDocument,readDocument} from '../src/core/document.js';
import {writeDocx,readDocx} from '../src/core/docx.js';
import {editFormat,editFormats,normalizedFormats} from '../src/core/formatting.js';
const paragraphs=['첫 문단이다.','둘째 문단이다.','', '마지막 문단이다.'];
const f=(text,size,bold=false)=>({paragraph:{left:18,right:6,firstLine:-12,align:'center'},runs:[{text:text.slice(0,2),style:{font:'맑은 고딕',latinFont:'Arial',size,bold,italic:true}},{text:text.slice(2),style:{font:'바탕',latinFont:'Georgia',size:11,bold:false,italic:false}}]});
for(const format of ['docx','hwpx'])test(format+' preserves multiple run styles, point sizes and hanging indents without changing text',()=>{const formatting=paragraphs.map(p=>f(p,16,true));const doc=readDocument(writeDocument(paragraphs,format,{formatting}),'원고.'+format);assert.deepEqual(doc.paragraphs,paragraphs);for(let i=0;i<paragraphs.length;i++){assert.deepEqual(doc.formatting[i].paragraph,formatting[i].paragraph);assert.equal(doc.formatting[i].runs[0].style.size,16);assert.equal(doc.formatting[i].runs[0].style.bold,true);assert.equal(doc.formatting[i].runs[0].style.italic,true);assert.equal(doc.formatting[i].runs[1].style.font,'바탕');assert.equal(doc.formatting[i].runs[1].style.latinFont,'Georgia');assert.equal(!!doc.formatting[i].runs[1].style.bold,false)}});
test('DOCX resolves defaults, paragraph inheritance, run styles and explicit false overrides',()=>{const files=unzipSync(writeDocx(['검증']));files['word/styles.xml']=strToU8(`<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:sz w:val="26"/></w:rPr></w:rPrDefault></w:docDefaults><w:style w:type="paragraph" w:styleId="Base"><w:pPr><w:ind w:left="720" w:firstLine="240"/></w:pPr><w:rPr><w:b/><w:rFonts w:eastAsia="바탕"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="Child"><w:basedOn w:val="Base"/><w:rPr><w:i/></w:rPr></w:style><w:style w:type="character" w:styleId="Large"><w:rPr><w:sz w:val="36"/></w:rPr></w:style></w:styles>`);files['word/document.xml']=strToU8(`<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:pPr><w:pStyle w:val="Child"/></w:pPr><w:r><w:t>하나</w:t></w:r><w:r><w:rPr><w:rStyle w:val="Large"/><w:b w:val="0"/></w:rPr><w:t>둘</w:t></w:r></w:p></w:body></w:document>`);const d=readDocx(zipSync(files));assert.deepEqual(d.paragraphs,['하나둘']);assert.deepEqual(d.formatting[0].paragraph,{left:36,firstLine:12});assert.equal(d.formatting[0].runs[0].style.size,13);assert.equal(d.formatting[0].runs[0].style.bold,true);assert.equal(d.formatting[0].runs[1].style.bold,false);assert.equal(d.formatting[0].runs[1].style.italic,true);assert.equal(d.formatting[0].runs[1].style.size,18)});
test('editing preserves unaffected run styles, inherits insertion style and keeps unchanged paragraphs',()=>{const text='빨강 파랑',fmt={paragraph:{firstLine:12},runs:[{text:'빨강 ',style:{bold:true}},{text:'파랑',style:{italic:true}}]};const after=editFormat(text,'빨강 정말 파랑!',fmt);assert.equal(after.runs.map(r=>r.text).join(''),'빨강 정말 파랑!');assert.equal(after.runs.at(-1).style.italic,true);assert.equal(after.paragraph.firstLine,12);const all=editFormats([text,'다음'],['추가',text,'다음'],[fmt,f('다음',22)]);assert.deepEqual(all[1],normalizedFormats([text],[fmt])[0]);assert.equal(all[2].runs[0].style.size,22)});
test('rich snapshots restore; paragraph edits are isolated and mixed selections export their own styles',async()=>{const worker=new Worker(new URL('./worker-adapter.js',import.meta.url));let id=0;const call=(type,payload={})=>new Promise((resolve,reject)=>{worker.once('message',r=>r.error?reject(Error(r.error)):resolve(r.result));worker.postMessage({id:++id,type,payload})});try{const old=['하나 원문','둘 원문','동일 문단'],rev=['하나 개고','둘 개고','동일 문단'];let model=await call('compare',{old:{name:'원문.hwpx',buffer:writeDocument(old,'hwpx',{formatting:old.map(p=>f(p,12))}).buffer},new:{name:'개고.docx',buffer:writeDocument(rev,'docx',{formatting:rev.map(p=>f(p,20,true))}).buffer}});const snapshot=await call('snapshot');model=await call('restore',{snapshot});let changes=model.scenes.flatMap(s=>s.segments.filter(g=>g.type==='change'));const choices=Object.fromEntries(changes.map((g,i)=>[g.id,i===0?'new':'old']));const merged=await call('export',{choices,format:'docx'});let d=readDocx(merged.buffer);assert.deepEqual(d.paragraphs,['하나 개고','둘 원문','동일 문단']);assert.deepEqual(d.formatting.map(f=>f.runs[0].style.size),[20,12,12]);const edited=await call('edit-paragraph',{fingerprint:model.fingerprint,index:0,text:'하나 직접 개고',choices});assert.equal(Object.values(edited.choices).filter(v=>v==='old').length,2);let raw=await call('export-revised');d=readDocument(raw.buffer,raw.name);assert.deepEqual(d.paragraphs,['하나 직접 개고','둘 개고','동일 문단']);assert.equal(d.formatting[0].runs[0].style.size,20);assert.deepEqual(d.formatting[1],readDocx(writeDocx(rev,{formatting:rev.map(p=>f(p,20,true))})).formatting[1]);await assert.rejects(call('edit-paragraph',{fingerprint:edited.comparison.fingerprint,index:99,text:'실패',choices:{}}),/문단/);const restored=await call('restore',{snapshot:await call('snapshot')});assert.equal(restored.fingerprint,edited.comparison.fingerprint);const split=await call('edit-paragraph',{fingerprint:restored.fingerprint,index:1,text:'둘 A\n둘 B',choices:{}});raw=await call('export-revised');assert.deepEqual(readDocument(raw.buffer,raw.name).paragraphs,['하나 직접 개고','둘 A','둘 B','동일 문단']);assert.equal(split.comparison.manuallyEdited,true)}finally{await worker.terminate()}});
test('format metadata is bounded and text mismatch does not corrupt output',()=>{const bad={paragraph:{left:Infinity,firstLine:99999},runs:[{text:'다른 글',style:{font:'x',size:NaN}}]};assert.deepEqual(readDocx(writeDocx(['원문'],{formatting:[bad]})).paragraphs,['원문']);assert.deepEqual(normalizedFormats(['원문'],[bad])[0].paragraph,{})});

test('format-only edits become selectable changes and survive DOCX/HWPX export',async()=>{const worker=new Worker(new URL('./worker-adapter.js',import.meta.url));let id=0;const call=(type,payload={})=>new Promise((resolve,reject)=>{worker.once('message',r=>r.error?reject(Error(r.error)):resolve(r.result));worker.postMessage({id:++id,type,payload})});try{const buffer=writeDocx(['같은 문장']);let model=await call('compare',{old:{name:'원문.docx',buffer:buffer.buffer},new:{name:'개고.hwpx',buffer:writeDocument(['같은 문장'],'hwpx').buffer}});const formatting={paragraph:{firstLine:18},runs:[{text:'같은 ',style:{bold:true,size:16,font:'바탕'}},{text:'문장',style:{italic:true,size:12,font:'바탕'}}]};let result=await call('edit-paragraph',{fingerprint:model.fingerprint,index:0,text:'같은 문장',choices:{},paragraphFormatting:formatting});model=result.comparison;const change=model.scenes[0].segments.find(g=>g.type==='change');assert.equal(change.description.kind,'format');for(const format of ['docx','hwpx']){const out=await call('export',{choices:{[change.id]:'new'},format});const d=readDocument(out.buffer,'저장.'+format);assert.equal(d.paragraphs[0],'같은 문장');assert.equal(d.formatting[0].paragraph.firstLine,18);assert.equal(d.formatting[0].runs[0].style.bold,true);assert.equal(d.formatting[0].runs[1].style.italic,true)}}finally{await worker.terminate()}});
