import {linkedChoices} from './paragraph-moves.js';
import {diffArrays,diffChars} from 'diff';
export const xmlEscape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
export function charStyle(s={}){const r={};for(const k of ['bold','italic'])if(typeof s[k]==='boolean')r[k]=s[k];for(const k of ['font','latinFont'])if(typeof s[k]==='string')r[k]=s[k].replace(/[\x00-\x1f]/g,'').slice(0,128);if(Number.isFinite(s.size)&&s.size>=1&&s.size<=400)r.size=s.size;return r}
export function paraStyle(s={}){const r={};for(const k of ['left','right','firstLine'])if(Number.isFinite(s[k])&&Math.abs(s[k])<=2000)r[k]=s[k];if(['left','right','center','justify'].includes(s.align))r.align=s.align;return r}
export function normalizeFormat(text,f){const runs=[];let offset=0;for(const r of (Array.isArray(f?.runs)?f.runs:[])){if(typeof r.text!=='string'||!text.startsWith(r.text,offset))return {paragraph:paraStyle(f?.paragraph),runs:[{text,style:{}}]};offset+=r.text.length;runs.push({text:r.text,style:charStyle(r.style)})}return {paragraph:paraStyle(f?.paragraph),runs:offset===text.length&&runs.length?runs:[{text,style:{}}]}}
export function normalizedFormats(paragraphs,formats){return paragraphs.map((p,i)=>normalizeFormat(p,formats?.[i]))}
export function editFormat(before,after,format){const f=normalizeFormat(before,format);let offset=0;const out=[];function styleAt(n){let end=0;for(const r of f.runs){end+=r.text.length;if(n<end)return r.style}return f.runs.at(-1)?.style||{}}function append(text,style){if(!text)return;if(out.length&&JSON.stringify(out.at(-1).style)===JSON.stringify(style))out.at(-1).text+=text;else out.push({text,style})}
 for(const d of diffChars(before,after,{timeout:100} )||[{removed:true,value:before},{added:true,value:after}]){if(d.removed){offset+=d.value.length;continue}if(d.added){append(d.value,styleAt(Math.max(0,offset-1)));continue}let remain=d.value;while(remain){let end=0;for(const r of f.runs){end+=r.text.length;if(end>offset)break}const n=Math.min(remain.length,Math.max(1,end-offset));append(remain.slice(0,n),styleAt(offset));offset+=n;remain=remain.slice(n)}}return {paragraph:f.paragraph,runs:out.length?out:[{text:'',style:styleAt(0)}]}}
export function editFormats(before,after,formats){let old=0;const out=[];let removed=[];for(const d of diffArrays(before,after)){if(d.removed){removed=d.value.map((text,i)=>({text,format:formats?.[old+i]}));old+=d.count}else if(d.added){d.value.forEach((p,i)=>{const base=removed[i]||removed.at(-1)||{text:'',format:formats?.[Math.max(0,old-1)]};out.push(editFormat(base.text,p,base.format))});removed=[]}else {removed=[];for(const p of d.value)out.push(normalizeFormat(p,formats?.[old++]));}}return out}
export function selectedFormats(model,choices,documents){choices=linkedChoices(model,choices);const out=[];for(const s of model.scenes)for(const g of s.segments){const useNew=g.type==='change'&&choices[g.id]==='new',side=useNew?'new':'old',range=g[useNew?'b':'a'],doc=documents[useNew?'revised':'original'];for(let n=range[0];n<range[1];n++)out.push(normalizeFormat(s[side][n],doc.formatting?.[s[side+'Start']+n]))}return out}
export function sliceFormat(text,format,start,end){const f=normalizeFormat(text,format),runs=[];let offset=0;for(const r of f.runs){const a=Math.max(0,start-offset),b=Math.min(r.text.length,end-offset);if(b>a)runs.push({text:r.text.slice(a,b),style:r.style});offset+=r.text.length}return {paragraph:f.paragraph,runs:runs.length?runs:[{text:'',style:f.runs[0]?.style||{}}]}}
export function styleRange(text,format,start,end,style){const f=normalizeFormat(text,format);if(start===end){start=0;end=text.length}return {paragraph:f.paragraph,runs:[...sliceFormat(text,f,0,start).runs.filter(r=>r.text),...sliceFormat(text,f,start,end).runs.map(r=>({...r,style:charStyle({...r.style,...style})})),...sliceFormat(text,f,end,text.length).runs.filter(r=>r.text)]}}
export function splitEditorFormat(text,format){let start=0;return text.split('\n').map(p=>{const f=sliceFormat(text,format,start,start+p.length);start+=p.length+1;return {...f,runs:f.runs.map(r=>({...r,text:r.text.replace(/\u2028/g,'\n')}))}})}
export function formatSignature(text,format){const f=normalizeFormat(text,format),runs=[];for(const r of f.runs){if(!r.text)continue;const s={bold:false,italic:false,font:'',latinFont:'',size:11,...r.style};if(runs.length&&JSON.stringify(runs.at(-1).style)===JSON.stringify(s))runs.at(-1).text+=r.text;else runs.push({text:r.text,style:s})}return JSON.stringify({paragraph:{left:0,right:0,firstLine:0,align:'left',...f.paragraph},runs})}
