// Structural matching is local and monotone: neither source text nor order is discarded.
export function heading(text){
 const value=text.trim().normalize('NFKC');if(value.length>90||/[\n\r]/.test(value))return null;
 const m=value.match(/^(?:제\s*)?([0-9]+|[일이삼사오육칠팔구십백]+)\s*(부|장|권)(?=$|\s|[:：.\-–—])\s*[:：.\-–—]?\s*(.*)$/)||value.match(/^(part|chapter|book)\s+([0-9]+|[ivxlcdm]+)(?=$|\s|[:.\-–—])\s*[:.\-–—]?\s*(.*)$/i);
 if(!m)return null;const english=/^(part|chapter|book)$/i.test(m[1]);const kind=english?({part:'부',chapter:'장',book:'권'}[m[1].toLowerCase()]):m[2];return {kind,number:(english?m[2]:m[1]).toLowerCase(),subtitle:m[3].trim(),title:value};
}
function grams(text){const s=text.replace(/\s+/g,'').normalize('NFC'),out=new Set(),step=1;for(let i=0;i<s.length-1;i+=step)out.add(s.slice(i,i+2));return out}
function similarity(a,b){if(!a.size||!b.size)return 0;let same=0;for(const x of a)if(b.has(x))same++;return 2*same/(a.size+b.size)}
export function sequenceMatch(a,b,score){const n=a.length,m=b.length;if(n*m>160000)return [...a.map((_,i)=>[i,null]),...b.map((_,j)=>[null,j])];const dp=Array.from({length:n+1},()=>new Float64Array(m+1)),scores=Array.from({length:n},()=>new Float64Array(m));for(let i=n-1;i>=0;i--)for(let j=m-1;j>=0;j--){const s=Math.max(0,score(a[i],b[j]));scores[i][j]=s;dp[i][j]=Math.max(dp[i+1][j],dp[i][j+1],dp[i+1][j+1]+s)}let i=0,j=0;const out=[];while(i<n||j<m){if(i<n&&j<m&&scores[i][j]>0&&Math.abs(dp[i][j]-dp[i+1][j+1]-scores[i][j])<1e-8)out.push([i++,j++]);else if(i<n&&(j===m||dp[i+1][j]>=dp[i][j+1]))out.push([i++,null]);else out.push([null,j++])}return out}
function units(scenes,kind){const out=[];for(let i=0;i<scenes.length;i++){const h=heading(scenes[i].paragraphs.find(p=>p.trim())||'');if(!out.length||h?.kind===kind)out.push({heading:h?.kind===kind?h:null,indices:[],body:[]});const unit=out.at(-1);unit.indices.push(i);unit.body.push(...scenes[i].paragraphs.filter(p=>p.trim()&&!heading(p)))}return out.map(u=>({...u,grams:grams(u.body.join('\n'))}))}
export function structuralPairs(oldScenes,newScenes,matchScenes){const hs=[...oldScenes,...newScenes].map(s=>heading(s.paragraphs.find(p=>p.trim())||''));const kind=['권','부','장'].find(k=>hs.some(h=>h?.kind===k));if(!kind)return matchScenes(oldScenes,newScenes).map(([a,b])=>({a,b}));const aa=units(oldScenes,kind),bb=units(newScenes,kind);const pairs=sequenceMatch(aa,bb,(a,b)=>{if(!a.heading&&!b.heading)return 1;if(!a.heading||!b.heading)return 0;const x=a.heading,y=b.heading,sim=similarity(a.grams,b.grams),differentTitles=x.subtitle&&y.subtitle&&x.subtitle!==y.subtitle;if(sim>=(differentTitles ? .8 : .42))return .7+sim;if(x.subtitle&&y.subtitle)return x.subtitle===y.subtitle?1.2:0;return x.number===y.number ? .45:0});const out=[];pairs.forEach(([a,b],group)=>{const old=a===null?null:aa[a],rev=b===null?null:bb[b],partTitle=rev?.heading?.title||old?.heading?.title||'머리말',partStatus=!old?'added':!rev?'deleted':'matched',partKey='part-'+group;const aligned=old&&rev?matchScenes(old.indices.map(i=>oldScenes[i]),rev.indices.map(i=>newScenes[i])):old?old.indices.map((_,i)=>[i,null]):rev.indices.map((_,i)=>[null,i]);for(const [x,y] of aligned)out.push({a:x===null?null:old.indices[x],b:y===null?null:rev.indices[y],partTitle,partStatus,partKey})});return out}
